-- ejercicio-practico-banco-azteca
DROP TABLE DENOMINACIONES;
DROP TABLE TRANSACCION_DETALLE;
DROP TABLE TRANSACIONES;
COMMIT;

-- GUARDA EL INVENTARIO (CUANTOS BILLETES - MONEDA HAY DE CADA DENOMINACION)
CREATE TABLE DENOMINACIONES(
ID          NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
TIPO        VARCHAR2 (20) NOT NULL,
CANTIDAD    NUMBER,
VALOR       NUMBER (10, 2),
ACTIVO      NUMBER DEFAULT 1, -- BOOLEAN: LA DENOMINACION ESTA DISPONIBLE?
CONSTRAINT ID_DENOMINACIONES_PK PRIMARY KEY (ID)
);

-- REGISTRO DE CADA RETIRO QUE SE HACE
CREATE TABLE TRANSACIONES(
ID                  NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
MONTO_SOLICITADO    NUMBER (12, 2),
MONTO_ENTEGADO      NUMBER (12, 2),
FECHA_HORA          TIMESTAMP DEFAULT SYSTIMESTAMP,
EXITOSO             NUMBER DEFAULT 1, -- BOOLEAN: LA TRANSACCION SE COMPLETO CORRECTAMENTE?
CONSTRAINT ID_TRANSACIONES_PK PRIMARY KEY (ID)
);

-- QUE DENOMINACIONES SE USARON EN CADA RETIRO
CREATE TABLE TRANSACCION_DETALLE(
ID                  NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
CANTIDAD_USADA      NUMBER,
ID_DENOMINACIONES   NUMBER NOT NULL,
ID_TRANSACIONES     NUMBER NOT NULL,
CONSTRAINT ID_DENOMINACIONES_FK FOREIGN KEY (ID_DENOMINACIONES) REFERENCES DENOMINACIONES(ID),
CONSTRAINT ID_TRANSACIONES_FK FOREIGN KEY (ID_TRANSACIONES) REFERENCES TRANSACIONES(ID)
);
COMMIT;

DESC DENOMINACIONES;
DESC TRANSACCION_DETALLE;
DESC TRANSACIONES;

-- DATOS INICIALES DEL CAJERO ($12,550)
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Billete', 2,   1000);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Billete', 5,   500);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Billete', 10,  200);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Billete', 20,  100);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Billete', 30,  50);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Billete', 40,  20);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Moneda',  50,  10);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Moneda',  100, 5);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Moneda',  200, 2);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Moneda',  300, 1);
INSERT INTO DENOMINACIONES (TIPO, CANTIDAD, VALOR) VALUES ('Moneda',  100, 0.50);
COMMIT;
